### ISSUE TITLE
Eigendecomposition on adjacent matrix

### ISSUE THREAD

**Issue by YanJiangJerry** [Louise-LuLin/GCL-SPAN#1]
Thank you so much for your reply. 
I have a following question please.

**Comment by YanJiangJerry** [comment]
Also, in Figure 8. the values of the original spectrum norm LGS(0) for Cora, Amazon-Photo, Wiki-CS, and PubMed are 24.88, 22.13, and 31.79, Is this the eigenvalue for the normed adjacent matrix? I calculate the norm for the laplacian for the Cora dataset and my value is 58, while the eigenvalue for the normed adjacent is 27 which is quite close. Could you clarify, please?

**Comment by Louise-LuLin** [comment]
Thank you for your interest to our work. 
Indeed we adopt a minor transition in the codes in order to reuse existing codes in GNNs. This however does not influence the optimization result of the paper's formulation: 
1. The code (https://github.com/Louise-LuLin/GCL-SPAN/blob/2f1272f2b533560881bc0e7895b27477422f259f/utils.py#L114) is calculating I+norm(A), using a renormalized trick in the GCN paper to stabilize the optimization procedure (discussed after Eq. (7) in https://arxiv.org/pdf/1609.02907.pdf).
2. The spectral change in the paper keeps the same using this calculation: suppose eigenvalues for norm(A) is a, and for norm(A+\delta) is a'. If using I+norm(A), the spectral change is ||1+a-1-a'||=||a-a'||; if using I-norm(A), the spectral change is ||1-a-1+a'||=||a-a'||.

**Comment by YanJiangJerry** [comment]
Thank you so much for your reply. 

May I ask is there any advantage for using the normalized A which is I + norm(A) instead of using Laplacian matrix for calculating eigenvalue Please？ I understand renormalized trick can use normalized adjacent matrix to simplify the complexity for the convolution operation, but i wonder how can it help the single eigen decomposition operation compared to decomposite the laplacian matrix？

Thank you very much and best wishes.

**Comment by Louise-LuLin** [comment]
Thanks for these good questions. 
I think there is no much difference in computational complexity in decomposing I+norm(A) or I-norm(A). The reason we choose the (renormalized) formal one is (1) to reuse existing codes, and (2) to stabilize the optimization with similar reason as in the GCN paper (avoiding numerical issues on gradients, since both I+norm(A) and I-norm(A) have eigenvalues in the range [0, 2]).
